version: '3.3'

services:
  bhajan-app:
    build: .
    image: serhiichechin/bhajan-app:latest
    ports:
      - "127.0.0.1:4000:4000"
      - "127.0.0.1:8005:8005"
      - "127.0.0.1:9200:9200"
    volumes:
      - bhajan-dynamodb:/data/dynamodb
      - bhajan-opensearch:/data/opensearch
      - .:/app
    environment:
      - NODE_ENV=development

volumes:
  bhajan-dynamodb:
  bhajan-opensearch: