version: '3.8'

services:
  bhajan-app:
    build: .
    image: serhiichechin/bhajan-app:latest
    ports:
      - "4000:4000"
      - "8005:8005"
      - "9200:9200"
    volumes:
      - bhajan-dynamodb:/data/dynamodb
      - bhajan-opensearch:/data/opensearch
      - ./web:/app/web:ro
    environment:
      - NODE_ENV=development

volumes:
  bhajan-dynamodb:
  bhajan-opensearch: