name: Deploy to Server

on:
  push:
    branches:
      - master  # or your default branch
  workflow_dispatch:  # Enables manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd cd /var/www/miracall.net/bhajan-server
            git pull
            yarn install
            docker compose down
            docker compose up -d 